
services:
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
    driver: local