name: TodoApp | Deploy Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  
jobs:
  deploy-staging:
    name: Deploy to staging environment

    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.actor }}/todoapp-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.actor }}/todoapp-frontend:latest

      - name: Setup VPN and test connection
        uses: ./.github/actions/vpn
        with:
          host: "${{ secrets.VPN_IP }}"
          port: "443"
          username: "${{ secrets.VPN_USERNAME }}"
          password: "${{ secrets.VPN_PASSWORD }}"
          ping_host: ${{ secrets.SSH_TEST_HOST }}

      - name: Sending deployment files to the staging server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./docker-compose.yaml,./deploy/**"
          target: ~/todoapp/
          port: 22

      - name: Deploying the application on the staging server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/todoapp
            docker compose down
            docker compose pull
            docker compose up -d