
name: TodoApp | Developpment Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-backend:
    name: Backend test executions

    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Setup Backend
        run: cd backend && npm install --prefer-offline

      - name: Package Audit
        run: cd backend && npm audit --audit-level critical

      - name: Lint the code
        run: cd backend && npm run lint

      - name: Unit tests
        run: cd backend && npm run test:ci
