name: TodoApp | Developpment Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  
jobs:
  # test-backend:
  #   name: Backend test executions

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Cloning the repository
  #       uses: actions/checkout@v4

  #     - name: Node installation
  #       uses: actions/setup-node@v4
  #       with:
  #         cache: "npm"
  #         cache-dependency-path: backend/package-lock.json

  #     - name: Setup Backend
  #       run: cd backend && npm ci --prefer-offline

  #     - name: Package Audit
  #       run: cd backend && npm audit --audit-level critical

  #     - name: Lint the code
  #       run: cd backend && npm run lint

  #     - name: Unit tests
  #       run: cd backend && npm run test:ci

  deploy-staging:
    name: Deploy to staging environment

    runs-on: ubuntu-latest
    # needs: test-backend

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v4

      # - name: Login to Docker Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push backend image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./backend
      #     push: true
      #     tags: ghcr.io/${{ github.actor }}/todoapp-backend:latest

      # - name: Build and push frontend image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./frontend
      #     push: true
      #     tags: ghcr.io/${{ github.actor }}/todoapp-frontend:latest

      - name: Setup VPN and test connection
        uses: ./.github/actions/vpn
        with:
          ip: "${{ secrets.VPN_IP }}"
          port: "443"
          username: "${{ secrets.VPN_USERNAME }}"
          password: "${{ secrets.VPN_PASSWORD }}"
          host_to_ping: ${{ secrets.SSH_TEST_HOST }}